package ru.spbau.textminer.text.feature;

public enum Link {
    COMPL, COMP, DIST, DAT_SUBJ, NUM_AUX, PRED, SUBJ_COPRED, REL, ADJOIN,
    REP_TIME, IZ, CONSTR, NUM_CONSTR, Q_AGENT, RAZ, EXPL, APP, COMPL_APP,
    ELPT, ADVMOD_TAUT, OBJ_ADVMOD, SENT_PRED, PL, AUX, NUM_COPRED, ADVMOD, REP,
    NA_COMPL, APPROX_NUM, SENT_S, ADD, OBJ_COPRED, AN, SUBJ_ADVMOD, S_CONJ, PREP, N_AGENT,
    DISTR, DESCR_DEF, PAN, D_APP, P_CONJ, N_COMPL, SPEC, COMPOSITE, AGENT,
    S, COMP_CONJ, CORR, NUM_APP, NOM_APP, ADR_LINK, LINK, DEF, TIME, ATTR,
    COMM_S, INTR, INF_CONJ, /*CONJ,*/ ELECT, APPROX_ORD, NUM//, UNKNOWN
}